# Generated by Django 4.2 on 2023-12-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='url',
        ),
        migrations.CreateModel(
            name='BulletPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullet_points', to='backend.note')),
            ],
        ),
    ]
