# Generated by Django 4.2 on 2023-11-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
