# Generated by Django 4.2 on 2023-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_content_note_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
