# Generated by Django 4.2 on 2023-11-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_topic_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('definition_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_category', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('sources', models.TextField()),
                ('tags', models.ManyToManyField(to='backend.tag')),
            ],
        ),
    ]
