# Generated by Django 4.2 on 2023-10-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_category_topic_url_alter_topic_description_analogy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogy',
            name='tags',
        ),
    ]
