# Generated by Django 4.2 on 2023-11-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
